---
version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    container_name: kibana
    environment:
#      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://192.168.99.100:9200
    ports:
      - "5601:5601"
