---
version: '3'
services:
  log_this_service:
    image: openjdk:8-alpine
    container_name: log-this
    command: java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /log-this.jar
    ports:
      - "8080:8080"
    volumes:
      - "/elk/log-this/target/log-this-0.0.1-SNAPSHOT.jar:/log-this.jar:ro"
      - "/tmp:/tmp"
